AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for centralized Liquibase changelog artifacts with cross-account access for trusted AWS accounts

Parameters:
  DevAccountId:
    Type: String
    Description: AWS Account ID for Dev environment
  IntAccountId:
    Type: String
    Description: AWS Account ID for Int environment
  UatAccountId:
    Type: String
    Description: AWS Account ID for UAT environment
  PreAccountId:
    Type: String
    Description: AWS Account ID for Pre environment
  ProdAccountId:
    Type: String
    Description: AWS Account ID for Production environment

Resources:
  LiquibaseArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: liquibase-artifacts-centralized
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LiquibaseArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LiquibaseArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowReadFromTrustedAccounts
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws-us-gov:iam::${152793237206}:root" #dev
                - !Sub "arn:aws-us-gov:iam::${241797054725}:root" #INT #uat #sharedacct
                - !Sub "arn:aws-us-gov:iam::${306952153860}:root" #preprod
                - !Sub "arn:aws-us-gov:iam::${306958713591}:root" #prod
            Action:
              - "s3:GetObject"
              - "s3:ListBucket"
            Resource:
              - !GetAtt LiquibaseArtifactBucket.Arn
              - !Sub "${LiquibaseArtifactBucket.Arn}/*"

Outputs:
  BucketName:
    Description: Name of the Liquibase artifact bucket
    Value: !Ref LiquibaseArtifactBucket

  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt LiquibaseArtifactBucket.Arn


























AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for centralized Liquibase changelog artifacts with cross-account access for VHB AWS accounts

Resources:
  LiquibaseArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: liquibase-artifacts-centralized
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  LiquibaseArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LiquibaseArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowReadFromVHBAccounts
            Effect: Allow
            Principal:
              AWS:
                - arn:aws-us-gov:iam::152793237206:root  # Dev
                - arn:aws-us-gov:iam::241797054725:root  # Int #Uat
                - arn:aws-us-gov:iam::306952153860:root  # PreProd
                - arn:aws-us-gov:iam::306958713591:root  # Prod
            Action:
              - "s3:GetObject"
              - "s3:ListBucket"
            Resource:
              - !GetAtt LiquibaseArtifactBucket.Arn
              - !Sub "${LiquibaseArtifactBucket.Arn}/*"

Outputs:
  BucketName:
    Description: Name of the Liquibase artifact bucket
    Value: !Ref LiquibaseArtifactBucket

  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt LiquibaseArtifactBucket.Arn
